### ISSUE TITLE
Mobile usability 

### ISSUE THREAD

**Issue by chantra** [icann/rfc-annotations#80]
On mobile, the annotations are rendered over the RFC text, and while there is a way to hide the RFC, there is no way to hide the annotations. See screenshot below.

![CE6386C8-079F-4CFD-A008-463D9C6C6D1F](https://user-images.githubusercontent.com/24572/185752955-46429d61-7a27-4829-8353-02950ee513dd.png)

**Comment by paulehoffman** [comment]
Fixed by #82. Manu: please check again and see if there is more that is needed. I note that we never intended this to work well on phones because we don't expect our target audience to be doing their work on phones, but if we can make this work better without sacrificing on normal screens, that's good.

**Comment by chantra** [comment]
Yes, much better. It is possible to zoom in/out allowing for better use of the screen estate.
Thanks.
![0591BD39-C147-41CA-A0BB-55B8EE4AE88C](https://user-images.githubusercontent.com/24572/185977853-4c3ec865-3848-4b00-a8ae-4cdc50033ed6.jpeg)
